use super::*;

pub(crate) fn requirement_api_schema() -> Value {
    json!({
        "version": 4,
        "flow": ["需求澄清", "开发中", "自测中", "测试中", "发布就绪", "经验总结", "已完成"],
        "statusValues": REQ_STATUSES,
        "subStatuses": SUB_REQ_STATUSES,
        "statusAliases": REQ_STATUS_ALIASES,
        "categoryValues": REQ_CATEGORIES,
        "tokens": requirement_token_specs_json(),
        "intents": [
            {"intent": "overview", "readTokens": intent_read_tokens("overview"), "writeTokens": intent_write_tokens("overview")},
            {"intent": "clarification", "readTokens": intent_read_tokens("clarification"), "writeTokens": intent_write_tokens("clarification")},
            {"intent": "status", "readTokens": intent_read_tokens("status"), "writeTokens": intent_write_tokens("status")},
            {"intent": "progress", "readTokens": intent_read_tokens("progress"), "writeTokens": intent_write_tokens("progress")},
            {"intent": "branch", "readTokens": intent_read_tokens("branch"), "writeTokens": intent_write_tokens("branch")},
            {"intent": "self-test", "readTokens": intent_read_tokens("self-test"), "writeTokens": intent_write_tokens("self-test")},
            {"intent": "release-check", "readTokens": intent_read_tokens("release-check"), "writeTokens": intent_write_tokens("release-check")},
            {"intent": "design", "readTokens": intent_read_tokens("design"), "writeTokens": intent_write_tokens("design")},
            {"intent": "config", "readTokens": intent_read_tokens("config"), "writeTokens": intent_write_tokens("config")},
            {"intent": "review", "readTokens": intent_read_tokens("review"), "writeTokens": intent_write_tokens("review")},
            {"intent": "experience-summary", "readTokens": intent_read_tokens("experience-summary"), "writeTokens": intent_write_tokens("experience-summary")}
        ],
        "operations": [
            {"operation": "setStatus", "writes": ["req.state"], "required": ["reqId", "status"], "optional": ["note", "dryRun"]},
            {"operation": "createSub", "endpoint": "POST /api/requirement/create-sub", "writes": ["req.meta", "req.state", "req.docs"], "required": ["parentReqId", "title"], "optional": ["slug", "owner", "summary", "dryRun"], "description": "从父需求拆出子需求（并行执行单元）；仅建记录，分支用 /api/requirement/sub/init-branches 初始化"},
            {"operation": "setCategory", "writes": ["req.state"], "required": ["reqId", "category"], "optional": ["dryRun"]},
            {"operation": "patchMeta", "writes": ["req.meta"], "required": ["reqId", "fields"], "allowedFields": ["title", "project", "owner", "startDate", "planRelease", "ones"]},
            {"operation": "appendNote", "writes": ["req.notes"], "required": ["reqId", "text"], "optional": ["title", "sessionId", "dryRun"]},
            {"operation": "recordEvent", "endpoint": "POST /api/requirement/events", "writes": ["events.jsonl", "req.notes"], "required": ["reqId", "type", "summary"], "optional": ["details", "evidence", "decisions", "todos", "relatedFiles", "relatedKnowledgeIds", "triggerTerms", "relatedRepos", "relatedTables", "relatedApis", "candidateType", "dedupeKey", "confidence", "target", "testCases", "idempotencyKey", "appendNote", "dryRun"]},
            {"operation": "writeDoc", "writes": ["token/docType"], "required": ["reqId", "token or docType", "content"], "optional": ["mode=replace|append", "dryRun"]},
            {"operation": "upsertSection", "writes": ["token/docType"], "required": ["reqId", "token or docType", "heading", "content"], "optional": ["dryRun"]},
            {"operation": "upsertNamedSection", "endpoint": "POST /api/requirement/sections/{section}", "writes": ["mapped doc section"], "required": ["reqId", "content"], "optional": ["heading", "docType", "token", "dryRun"]}
        ],
        "eventTypes": ["progress", "decision", "knowledgeReference", "learningCandidate", "skillImprovementCandidate", "issueFound", "rootCause", "testResult", "statusTransition"],
        "groups": {
            "description": "引用式需求组：组需求目录下 group.json 通过 reqId 引用独立存在的成员需求，不做目录搬家；组状态为派生值 = min(成员需求流状态)，不能手动 setStatus；session 绑定组时自动绑定/解绑所有成员。",
            "groupFile": "group.json (version=1, releasePolicy=together|independent, members=[{reqId, note?}])",
            "create": "POST /api/requirements 传 members=[{reqId}]（可选 releasePolicy）创建组；成员必须已存在且非组，不支持组嵌套",
            "readonlyStatus": true,
            "context": "GET /api/requirement/context 对组需求额外返回 group 块（aggregatedStatus/bottleneck/members）"
        },
        "subRequirements": {
            "description": "子需求：从大需求（父需求）中途拆出的并行执行单元，提高大需求并行开发速度；与需求组互补（组=已建需求中途聚合，子需求=大需求中途拆分）。目录平铺，ID=<父票号>-S<n>[-slug]（如 WMS-049-S1-fix-logging），n 在父需求内递增且不复用；父子关系记在子需求 meta.md 的 parent-req-id（source of truth）。",
            "statuses": "需求创建 → 开发中 → 已合入；需求创建/开发中可直接已取消（终态不可重开）；无门禁，合入主需求不校验 Review Gate（代码审查在父需求内统一走）",
            "boundary": "子需求不绑 ONES/plan-release/issues、不切类别；环境集成（合 test/UAT）、发布、经验总结都在父需求做；子分支合回父分支，不直接碰共享环境分支",
            "create": "POST /api/requirement/create-sub（parentReqId+title+slug?+summary?）；仅建记录不建分支；自动复制父需求 background/technical-plan/impact/test 文档作快照起点并标注快照来源",
            "branches": "POST /api/requirement/sub/init-branches：以父需求 branches.json 为模板派生子分支 <父分支>-sub<n>（每仓，可删减 repo 子集），baseRef=父分支，可一键建分支+worktree",
            "merge": "POST /api/requirement/sub/sync-parent 同步父分支最新成果到子分支（冲突在子分支解）；POST /api/requirement/sub/merge-to-parent 合回父分支（成功后自动推进已合入）",
            "list": "GET /api/requirements 默认不含子需求，传 includeSubs=true 包含；父需求 DTO 内嵌 subReqs 回填"
        },
        "agentContext": {
            "endpoint": "GET /api/requirement/context?id=<reqId>&for=agent&intent=<intent>&budget=2000",
            "description": "returns compressed summary docs, recent structured events, recommended write APIs, fixedPhasePrompt and statePhasePrompt"
        },
        "rules": [
            "需求澄清阶段合并旧的需求对齐和方案设计：先做需求点拆解与关联性检查，关联性明显低的要点通过父需求+叶子子需求拆分为独立需求供多 agent 并行，再读业务知识/经验、初步调查代码，输出 background.md、technical-plan.md、notes.md 的最小闭环；alignment/impact/memory 仅历史兼容。" ,
            "经验总结阶段替代旧待上线状态：识别本次需求暴露的 skill、业务知识、经验和流程改进，并把已落地/待落地区分记录到 experience-summary.md。",
            "Agent should call context with for=agent for most work; use token context only when the compressed summary is insufficient.",
            "Use recordEvent for facts, evidence, test results, decisions and todos; it stores events.jsonl and can append notes.md.",
            "Use sections/{section} or upsertSection for targeted document updates instead of replacing full markdown files.",
            "Maintain req.technicalPlan throughout implementation: update the global approach before/after non-trivial code changes so humans can review direction before reading diffs.",
            "Every phase context includes prompts/phase-common.md as fixedPhasePrompt; state-specific prompts stay in prompts/phase-*.md as statePhasePrompt.",
            "During all phases, record referenced knowledge/experience IDs as knowledgeReference events and reusable findings as learningCandidate or skillImprovementCandidate events when current-session details may help later experience summary.",
            "Requirements have a source attribute: 产品推动 (default) or 开发推动. For 开发推动 requirements, QA cannot ask product for test scope, so the dev must fill test-scenario.md (需求说明 + 开发评估的测试范围 + 测试覆盖场景) before the requirement can enter 测试中; the status API rejects the transition otherwise.",
            "Online issue requirements use lightweight statuses 排查中/已定位/已修复/已复盘/已关闭 and do not need the strict normal requirement lifecycle unless converted to category=需求.",
            "Online/test issues CAN register branches.json and write reproduction/test code on requirement branches; merge targets are limited to test/UAT env branches (backend master, frontend production are production branches and get blocked at merge time; prod MR API rejects issues). Formal production fix still goes through a normal requirement bound via the meta.md issues field; when that requirement reaches 经验总结 or later, linked issues in 排查中/已定位 are auto-advanced to 已修复 by agent-panel.",
            "Agent should call edit-plan before selecting files for non-trivial requirement edits.",
            "state.json is the source of truth for status/category; do not direct-edit it.",
            "Use appendNote for free-form progress logs; avoid replacing notes.md.",
            "Use branches.json as machine-readable branch scope; branch.md is legacy/human narrative when present.",
            "引用式需求组（group.json）：多个高关联独立需求可组队作为整体开发，组状态 = min(成员状态) 派生只读；推进组进度 = 推进瓶颈成员；session 绑定组时自动绑定所有成员；不要对组需求调用 setStatus，也不要把组文档（整体目标/发布顺序）重复写进成员文档。"
        ]
    })
}

fn requirement_token_specs_json() -> Vec<Value> {
    vec![
        token_spec(
            "req.meta",
            "meta.md",
            None,
            "stable identity fields and human summary",
            true,
            vec!["patchMeta"],
        ),
        token_spec(
            "req.state",
            STATE_FILE,
            None,
            "status/category and transition history; state source of truth",
            true,
            vec!["setStatus", "setCategory"],
        ),
        token_spec(
            "req.background",
            "background.md",
            Some("background"),
            "developer-facing business background, goal, scope, current behavior, key rules and decisions",
            true,
            vec!["writeDoc", "upsertSection"],
        ),
        token_spec(
            "req.memory",
            "memory.md",
            Some("memory"),
            "short agent-facing lifecycle memory and compressed context",
            true,
            vec!["writeDoc", "upsertSection"],
        ),
        token_spec(
            "req.branch",
            "branch.md",
            Some("branch"),
            "human-readable branch and merge narrative",
            true,
            vec!["writeDoc", "upsertSection"],
        ),
        token_spec(
            "req.branchScope",
            BRANCH_SCOPE_FILE,
            None,
            "machine-readable repo/branch scope for diff/deploy automation",
            true,
            vec![],
        ),
        token_spec(
            "req.configChanges",
            "config-changes.md",
            Some("config-changes"),
            "DB/Apollo/Nacos/RocketMQ/config changes",
            true,
            vec!["writeDoc", "upsertSection"],
        ),
        token_spec(
            "req.releaseManifest",
            "release-manifest.md",
            Some("release-manifest"),
            "always-visible release change manifest: DB tables, configs, topics, groups, jobs, APIs and manual release actions",
            true,
            vec!["writeDoc", "upsertSection"],
        ),
        token_spec(
            "req.attachments",
            "attachments/",
            None,
            "non-code release assets attached to the requirement: SQL files, config exports, runbooks, screenshots and manual operation evidence",
            false,
            vec![],
        ),
        token_spec(
            "req.technicalPlan",
            "technical-plan.md",
            Some("technical-plan"),
            "agent-maintained implementation plan for global design, touched code, risks and validation before human diff review",
            true,
            vec!["writeDoc", "upsertSection"],
        ),
        token_spec(
            "req.incident",
            "incident.md",
            Some("incident"),
            "online-issue incident profile: symptom, discovery channel, env, time window, impact scope, reproduction steps and timeline",
            true,
            vec!["writeDoc", "upsertSection"],
        ),
        token_spec(
            "req.rootCause",
            "root-cause.md",
            Some("root-cause"),
            "online-issue root cause and fix decision: root cause, user-verifiable evidence chain, impact, fix path decision, temporary actions and rollback",
            true,
            vec!["writeDoc", "upsertSection"],
        ),
        token_spec(
            "req.impact",
            "impact.md",
            Some("impact"),
            "impact assessment, core-link risk, rollback plan",
            true,
            vec!["writeDoc", "upsertSection"],
        ),
        token_spec(
            "req.test",
            "test.md",
            Some("test"),
            "test scenarios, self-test/UAT evidence and confidence",
            true,
            vec!["writeDoc", "upsertSection"],
        ),
        token_spec(
            "req.notes",
            "notes.md",
            Some("notes"),
            "append-only progress, decisions and pitfalls",
            false,
            vec!["appendNote", "writeDoc", "upsertSection"],
        ),
        token_spec(
            "req.review",
            "review.md",
            Some("review"),
            "code review and pre-release review summary",
            false,
            vec!["writeDoc", "upsertSection"],
        ),
        token_spec(
            "req.releaseCheck",
            "release-check.md",
            Some("release-check"),
            "release readiness checklist and blocking items",
            false,
            vec!["writeDoc", "upsertSection"],
        ),
        token_spec(
            "req.experienceSummary",
            "experience-summary.md",
            Some("experience-summary"),
            "post-requirement capability evolution summary for knowledge, experience and skill improvements",
            false,
            vec!["writeDoc", "upsertSection"],
        ),
        token_spec(
            "req.alignment",
            "alignment.md",
            Some("alignment"),
            "requirement clarification notes, PRD interpretation and open questions",
            true,
            vec!["writeDoc", "upsertSection"],
        ),
        token_spec(
            "req.prd",
            "prd.md",
            Some("prd"),
            "source PRD or product notes",
            false,
            vec!["writeDoc", "upsertSection"],
        ),
        token_spec(
            "req.codeReview",
            CODE_REVIEW_FILE,
            None,
            "large generated code-review artifact; read only by explicit intent",
            false,
            vec![],
        ),
    ]
}

pub(crate) fn token_spec(
    token: &str,
    file: &str,
    doc_type: Option<&str>,
    role: &str,
    standard: bool,
    write_ops: Vec<&str>,
) -> Value {
    json!({
        "token": token,
        "file": file,
        "docType": doc_type,
        "role": role,
        "standard": standard,
        "writeOps": write_ops,
    })
}
